export const SHOW_JOKES = "SHOW_JOKES";
export const SHOW_JOKES_FULFILLED = "SHOW_JOKES_FULFILLED";
export const SHOW_JOKES_REJECTED = "SHOW_JOKES_REJECTED";
export const SHOW_JOKES_PENDING = "SHOW_JOKES_PENDING";
export const SHOW_PREVIOUS_JOKES = "SHOW_PREVIOUS_JOKES";
export const ACTION_ON_JOKES = "ACTION_ON_JOKES";
export const MOVE_TO_NEXT_JOKE = "MOVE_TO_NEXT_JOKE";
export const SHOW_SUMMARY = "SHOW_SUMMARY";
